#+TITLE: Hi, Dan here!
#+DATE: <2025-01-04>
#+SUBTITLE: About me
#+LANGUAGE: en
#+DESCRIPTION: Jack of all trades, master of some.
#+KEYWORDS: dan dee, interests, philosopher, designer, generalist, entrepreneur, multipotentialite, amateur
#+HTML_HEAD_EXTRA: <link rel="canonical" href="https://monkeyjunglejuice.github.io/bio.html">
#+SETUPFILE: ./static/setup.org
#+OPTIONS:

#+TOC: headlines 0

I've got a love for examining phenomena from uncommon perspectives, cross-linking patterns, and a deep fascination for things 'bottom-up'.

Professionally, I'm best described as a generalist designer and entrepreneur. Before co-founding a footwear brand and re-thinking shoes from the ground up, I specialized in brand design, UX/UI design, followed by conversion rate optimization -- this area intrigued me due to its empirical methods of analyzing human decision-making and the measurable impact of design on persuasion. Before that, I pursued a military career, where I made it to the rank of staff seargent in the military police; I was younger and much more stupid back then, but it also means I learned a lot from that experience).

Considering myself by what I actually do most of the time, I'm nowadays much more an "amateur" (in the original meaning of the word) rather than a "professional". That's liberating for once; but more importantly, it makes life meaningful.

The range of my interests is a bit all over the place:
- Metaphysics and Ontology
- Computation and artificial life (not to confuse with "AI")
- Programming languages and paradigms, particularly Lisp
- Emacs (check out my starterkit and Emacs themes on Github)
- Longboarding and old-school skateboarding
- Muay Thai training, philosophy and theory
- Korean traditional archery

I care about:
- Deepest about these who don't have a voice, that means first and foremost animal welfare and animal rights
- Preserving, restoring and improving the natural environment
- Migitating anthropocentrism
- Open source and free software

-----
CREDITS:
Static site generator: [[https://www.gnu.org/software/emacs/][Emacs]] with [[https://orgmode.org/features.html#publishing][Org-mode]]
CSS frameworks: [[http://necolas.github.io/normalize.css/][normalize.css]] and [[https://github.com/oxalorg/sakura][sakura]]
